/**
 * Country name to flag emoji mapping.
 * Use getFlagForCountry() for lookup so jurisdiction name variants (e.g. "Antigua & Barbuda")
 * can be matched to stored keys (e.g. "Antigua and Barbuda").
 * Only use these flags; do not invent emojis for countries not in this list.
 */

export interface CountryFlag {
	country: string;
	flag: string;
}

export const COUNTRY_FLAGS: readonly CountryFlag[] = [
	{ country: "Afghanistan", flag: "🇦🇫" },
	{ country: "Albania", flag: "🇦🇱" },
	{ country: "Algeria", flag: "🇩🇿" },
	{ country: "Andorra", flag: "🇦🇩" },
	{ country: "Angola", flag: "🇦🇴" },
	{ country: "Antigua and Barbuda", flag: "🇦🇬" },
	{ country: "Argentina", flag: "🇦🇷" },
	{ country: "Armenia", flag: "🇦🇲" },
	{ country: "Australia", flag: "🇦🇺" },
	{ country: "Austria", flag: "🇦🇹" },
	{ country: "Azerbaijan", flag: "🇦🇿" },
	{ country: "Bahamas", flag: "🇧🇸" },
	{ country: "Bahrain", flag: "🇧🇭" },
	{ country: "Bangladesh", flag: "🇧🇩" },
	{ country: "Barbados", flag: "🇧🇧" },
	{ country: "Belarus", flag: "🇧🇾" },
	{ country: "Belgium", flag: "🇧🇪" },
	{ country: "Belize", flag: "🇧🇿" },
	{ country: "Benin", flag: "🇧🇯" },
	{ country: "Bhutan", flag: "🇧🇹" },
	{ country: "Bolivia", flag: "🇧🇴" },
	{ country: "Bosnia and Herzegovina", flag: "🇧🇦" },
	{ country: "Botswana", flag: "🇧🇼" },
	{ country: "Brazil", flag: "🇧🇷" },
	{ country: "British Virgin Islands", flag: "🇻🇬" },
	{ country: "Brunei", flag: "🇧🇳" },
	{ country: "Bulgaria", flag: "🇧🇬" },
	{ country: "Burkina Faso", flag: "🇧🇫" },
	{ country: "Burundi", flag: "🇧🇮" },
	{ country: "Cambodia", flag: "🇰🇭" },
	{ country: "Cameroon", flag: "🇨🇲" },
	{ country: "Canada", flag: "🇨🇦" },
	{ country: "Cape Verde", flag: "🇨🇻" },
	{ country: "Cayman Islands", flag: "🇰🇾" },
	{ country: "Central African Republic", flag: "🇨🇫" },
	{ country: "Chad", flag: "🇹🇩" },
	{ country: "Chile", flag: "🇨🇱" },
	{ country: "China", flag: "🇨🇳" },
	{ country: "Colombia", flag: "🇨🇴" },
	{ country: "Comoros", flag: "🇰🇲" },
	{ country: "Congo", flag: "🇨🇬" },
	{ country: "Costa Rica", flag: "🇨🇷" },
	{ country: "Croatia", flag: "🇭🇷" },
	{ country: "Cuba", flag: "🇨🇺" },
	{ country: "Cyprus", flag: "🇨🇾" },
	{ country: "Czech Republic", flag: "🇨🇿" },
	{ country: "Denmark", flag: "🇩🇰" },
	{ country: "Djibouti", flag: "🇩🇯" },
	{ country: "Dominica", flag: "🇩🇲" },
	{ country: "Dominican Republic", flag: "🇩🇴" },
	{ country: "Ecuador", flag: "🇪🇨" },
	{ country: "Egypt", flag: "🇪🇬" },
	{ country: "El Salvador", flag: "🇸🇻" },
	{ country: "Equatorial Guinea", flag: "🇬🇶" },
	{ country: "Eritrea", flag: "🇪🇷" },
	{ country: "Estonia", flag: "🇪🇪" },
	{ country: "Eswatini", flag: "🇸🇿" },
	{ country: "Ethiopia", flag: "🇪🇹" },
	{ country: "Fiji", flag: "🇫🇯" },
	{ country: "Finland", flag: "🇫🇮" },
	{ country: "France", flag: "🇫🇷" },
	{ country: "Gabon", flag: "🇬🇦" },
	{ country: "Gambia", flag: "🇬🇲" },
	{ country: "Georgia", flag: "🇬🇪" },
	{ country: "Germany", flag: "🇩🇪" },
	{ country: "Ghana", flag: "🇬🇭" },
	{ country: "Greece", flag: "🇬🇷" },
	{ country: "Grenada", flag: "🇬🇩" },
	{ country: "Guatemala", flag: "🇬🇹" },
	{ country: "Guinea", flag: "🇬🇳" },
	{ country: "Guinea-Bissau", flag: "🇬🇼" },
	{ country: "Guyana", flag: "🇬🇾" },
	{ country: "Haiti", flag: "🇭🇹" },
	{ country: "Honduras", flag: "🇭🇳" },
	{ country: "Hong Kong", flag: "🇭🇰" },
	{ country: "Hungary", flag: "🇭🇺" },
	{ country: "Iceland", flag: "🇮🇸" },
	{ country: "India", flag: "🇮🇳" },
	{ country: "Isle of Man", flag: "🇮🇲" },
	{ country: "Indonesia", flag: "🇮🇩" },
	{ country: "Iran", flag: "🇮🇷" },
	{ country: "Iraq", flag: "🇮🇶" },
	{ country: "Ireland", flag: "🇮🇪" },
	{ country: "Israel", flag: "🇮🇱" },
	{ country: "Italy", flag: "🇮🇹" },
	{ country: "Jamaica", flag: "🇯🇲" },
	{ country: "Japan", flag: "🇯🇵" },
	{ country: "Jordan", flag: "🇯🇴" },
	{ country: "Kazakhstan", flag: "🇰🇿" },
	{ country: "Kenya", flag: "🇰🇪" },
	{ country: "Kiribati", flag: "🇰🇮" },
	{ country: "Kuwait", flag: "🇰🇼" },
	{ country: "Kyrgyzstan", flag: "🇰🇬" },
	{ country: "Laos", flag: "🇱🇦" },
	{ country: "Latvia", flag: "🇱🇻" },
	{ country: "Lebanon", flag: "🇱🇧" },
	{ country: "Lesotho", flag: "🇱🇸" },
	{ country: "Liberia", flag: "🇱🇷" },
	{ country: "Libya", flag: "🇱🇾" },
	{ country: "Liechtenstein", flag: "🇱🇮" },
	{ country: "Lithuania", flag: "🇱🇹" },
	{ country: "Luxembourg", flag: "🇱🇺" },
	{ country: "Madagascar", flag: "🇲🇬" },
	{ country: "Malawi", flag: "🇲🇼" },
	{ country: "Malaysia", flag: "🇲🇾" },
	{ country: "Maldives", flag: "🇲🇻" },
	{ country: "Mali", flag: "🇲🇱" },
	{ country: "Malta", flag: "🇲🇹" },
	{ country: "Marshall Islands", flag: "🇲🇭" },
	{ country: "Mauritania", flag: "🇲🇷" },
	{ country: "Mauritius", flag: "🇲🇺" },
	{ country: "Mexico", flag: "🇲🇽" },
	{ country: "Micronesia", flag: "🇫🇲" },
	{ country: "Moldova", flag: "🇲🇩" },
	{ country: "Monaco", flag: "🇲🇨" },
	{ country: "Mongolia", flag: "🇲🇳" },
	{ country: "Montenegro", flag: "🇲🇪" },
	{ country: "Morocco", flag: "🇲🇦" },
	{ country: "Mozambique", flag: "🇲🇿" },
	{ country: "Myanmar", flag: "🇲🇲" },
	{ country: "Namibia", flag: "🇳🇦" },
	{ country: "Nauru", flag: "🇳🇷" },
	{ country: "Nepal", flag: "🇳🇵" },
	{ country: "Netherlands", flag: "🇳🇱" },
	{ country: "New Zealand", flag: "🇳🇿" },
	{ country: "Nicaragua", flag: "🇳🇮" },
	{ country: "Niger", flag: "🇳🇪" },
	{ country: "Nigeria", flag: "🇳🇬" },
	{ country: "North Korea", flag: "🇰🇵" },
	{ country: "North Macedonia", flag: "🇲🇰" },
	{ country: "Norway", flag: "🇳🇴" },
	{ country: "Oman", flag: "🇴🇲" },
	{ country: "Pakistan", flag: "🇵🇰" },
	{ country: "Palau", flag: "🇵🇼" },
	{ country: "Panama", flag: "🇵🇦" },
	{ country: "Papua New Guinea", flag: "🇵🇬" },
	{ country: "Paraguay", flag: "🇵🇾" },
	{ country: "Peru", flag: "🇵🇪" },
	{ country: "Philippines", flag: "🇵🇭" },
	{ country: "Poland", flag: "🇵🇱" },
	{ country: "Portugal", flag: "🇵🇹" },
	{ country: "Puerto Rico", flag: "🇵🇷" },
	{ country: "Qatar", flag: "🇶🇦" },
	{ country: "Romania", flag: "🇷🇴" },
	{ country: "Russia", flag: "🇷🇺" },
	{ country: "Rwanda", flag: "🇷🇼" },
	{ country: "Saudi Arabia", flag: "🇸🇦" },
	{ country: "Saint Lucia", flag: "🇱🇨" },
	{ country: "Saint Vincent & Grenadines", flag: "🇻🇨" },
	{ country: "Senegal", flag: "🇸🇳" },
	{ country: "Serbia", flag: "🇷🇸" },
	{ country: "Seychelles", flag: "🇸🇨" },
	{ country: "Singapore", flag: "🇸🇬" },
	{ country: "Slovakia", flag: "🇸🇰" },
	{ country: "South Africa", flag: "🇿🇦" },
	{ country: "South Korea", flag: "🇰🇷" },
	{ country: "Spain", flag: "🇪🇸" },
	{ country: "Sri Lanka", flag: "🇱🇰" },
	{ country: "Sweden", flag: "🇸🇪" },
	{ country: "Switzerland", flag: "🇨🇭" },
	{ country: "Thailand", flag: "🇹🇭" },
	{ country: "Turkey", flag: "🇹🇷" },
	{ country: "Ukraine", flag: "🇺🇦" },
	{ country: "United Arab Emirates", flag: "🇦🇪" },
	{ country: "United Kingdom", flag: "🇬🇧" },
	{ country: "United States", flag: "🇺🇸" },
	{ country: "Vanuatu", flag: "🇻🇺" },
	{ country: "Vietnam", flag: "🇻🇳" },
	{ country: "Yemen", flag: "🇾🇪" },
	{ country: "Zambia", flag: "🇿🇲" },
	{ country: "Zimbabwe", flag: "🇿🇼" },
];

const flagByCountry = new Map<string, string>(
	COUNTRY_FLAGS.map(({ country, flag }) => [country.toLowerCase().trim(), flag])
);

/** Normalize jurisdiction/country names used in the app to keys in COUNTRY_FLAGS. */
const JURISDICTION_ALIASES: Record<string, string> = {
	"Antigua & Barbuda": "Antigua and Barbuda",
};

/**
 * Returns the flag emoji for a country/jurisdiction name, or null if not in the stored data.
 * Only uses flags from COUNTRY_FLAGS; does not invent emojis.
 */
export function getFlagForCountry(jurisdictionOrCountry: string): string | null {
	const normalized = jurisdictionOrCountry.trim();
	const alias = JURISDICTION_ALIASES[normalized];
	const key = (alias ?? normalized).toLowerCase();
	return flagByCountry.get(key) ?? null;
}
