export const boyarData = {
  subtabs: ["Organizational Identity","Client Intimacy","Pricing & Execution","Acquisition Engine","Why This Scales"],
  panels: [
    `<div class="cl-yhdr"><h2>Organizational <span class="cl-red">Identity</span></h2><div class="cl-yhdr-obj">What the firm exists to do — and why that singular focus compounds into structural advantage that neither tier can replicate.</div></div>
    <div class="cl-block"><div class="cl-block-t">The Founding Distinction</div><p>The distinction begins with what the firm exists to do. Mass incorporators exist to process formations. Legacy firms exist to practice law, manage pensions, or run enterprise operations — with structuring as one capability among many. Boyar exists to do one thing: build the most rigorous, most intimate, most globally capable boutique cross-border structuring and advisory practice in the market. Cross-border structuring, corporate formation, licensing advisory, trust services, banking introductions, fund administration, and citizenship planning are not subsets of something else at Boyar. They are not a department within a larger organism. They are the organism. This singular focus creates compounding advantages that are invisible in Year 1 but transformative by Year 5.</p></div>
    <div class="cl-mc"><h4>When structuring is your entire business, <span class="cl-red">you invest differently.</span></h4><p>You build jurisdiction comparison frameworks because that's your core advisory tool, not a side project. You develop licensing expertise because it's a primary revenue line, not a niche offering buried in a regulatory department. You cultivate banking relationships with the intensity of a firm whose introduction capability directly determines client satisfaction, not with the casual attention of a firm where banking introductions are a courtesy extended alongside the real engagement. Every dollar of investment, every hour of the founder's attention, every technology decision, every hire, every partnership — all of it is directed toward this singular purpose.</p></div>
    <div class="cl-block"><div class="cl-block-t">The Competitive Insight</div><p>No single competitor combines boutique advisory depth, multi-jurisdictional licensing capability, and a digital-native client experience. Boyar's positioning in the intersection of all three is deliberate. Dixcart has depth but no UAE, APAC, or licensing presence. Amicorp has scale but not boutique attention. Astons has UAE presence but no structuring depth. Ocra has formation capability but no advisory at all. Rosemont has advisory quality but single-jurisdiction concentration. The competitive gap that makes this positioning sustainable: mass incorporators cannot profitably add advisory depth — their economic model breaks the moment they add a human advisory layer. Legacy firms cannot economically deliver boutique attention to mid-market mandates — their overhead and competing priorities make it structurally impossible.</p></div>`,

    `<div class="cl-yhdr"><h2>Client <span class="cl-red">Intimacy</span></h2><div class="cl-yhdr-obj">The advisory quality that neither tier can match — not because they lack expertise, but because they lack the structural incentive to deploy it at the client level.</div></div>
    <div class="cl-mc"><h4>Named-advisor model creates <span class="cl-red">anticipatory advisory.</span></h4><p>Boyar's named-advisor model means the advisor doesn't just understand the client's current structure — they understand the client's intent. Where is the business heading in three years? Is the founder likely to raise institutional capital, and if so, does the current holding structure accommodate a clean cap table? Is the family likely to relocate again, and does the trust jurisdiction account for that mobility? Are there licensing requirements on the horizon that should inform the choice of operating entity jurisdiction today, not retroactively? This is anticipatory advisory — structuring not just for the present need but for the foreseeable evolution of the client's business and personal circumstances. Legacy firms have the expertise to do this but not the economic incentive — when an engagement is one of 200 on a partner's desk, the structuring conversation defaults to the efficient answer rather than the optimal one.</p></div>
    <div class="cl-mc"><h4>Efficient answers solve today's problem. <span class="cl-red">Optimal answers prevent tomorrow's.</span></h4><p>A legacy firm will form your holding company in the jurisdiction that fits the immediate brief. Boyar will form your holding company in the jurisdiction that fits the immediate brief, the Series B you're planning in eighteen months, the personal relocation you're considering in two years, and the family trust restructuring that will become necessary when your eldest child turns twenty-five. The formation fee might be similar. The long-term value to the client — and the long-term revenue to Boyar through the cascade of engagements that arise from that forward-looking architecture — is fundamentally different.</p></div>
    <div class="cl-kpis"><div class="cl-kpi"><div class="cl-kpi-l">Single-vertical 3yr LTV</div><div class="cl-kpi-v">~$18K</div></div><div class="cl-kpi"><div class="cl-kpi-l">Dual-vertical 3yr LTV</div><div class="cl-kpi-v">~$38K</div></div><div class="cl-kpi"><div class="cl-kpi-l">Multi-vertical 3yr LTV</div><div class="cl-kpi-v cl-r">~$69K</div></div><div class="cl-kpi"><div class="cl-kpi-l">100 single-vertical clients</div><div class="cl-kpi-v">$1.8M</div></div><div class="cl-kpi"><div class="cl-kpi-l">100 multi-vertical clients</div><div class="cl-kpi-v cl-r">$6.9M</div></div><div class="cl-kpi"><div class="cl-kpi-l">Retention at 3+ verticals</div><div class="cl-kpi-v">92%+</div></div></div>`,

    `<div class="cl-yhdr"><h2>Pricing &amp; <span class="cl-red">Execution Model</span></h2><div class="cl-yhdr-obj">Law-firm-quality execution at boutique pricing — coordinated by a single named advisor who understands the full picture, delivered by a vetted network of jurisdiction specialists.</div></div>
    <div class="cl-stats"><div class="cl-stat"><div class="cl-stat-lbl">vs Tier 3 Pricing</div><div class="cl-stat-val">15–25% lower</div></div><div class="cl-stat"><div class="cl-stat-lbl">Advisory Depth</div><div class="cl-stat-val">Equivalent</div></div><div class="cl-stat"><div class="cl-stat-lbl">Formation Conversion</div><div class="cl-stat-val cl-r">30% to Full Structure</div></div><div class="cl-stat"><div class="cl-stat-lbl">Full Structure Revenue</div><div class="cl-stat-val cl-r">$29,700 per mandate</div></div></div>
    <div class="cl-block"><div class="cl-block-t">The Overhead Equation</div><p>Boyar's pricing sits slightly below the legacy law firms and institutional TCSPs — typically 15–25% lower for comparable scope — but delivers the same depth of structuring advice, the same quality of governance documentation, and the same caliber of banking introductions. Boyar's vetted partners within the Boyar Network include professionals who are members of, trained at, or formerly with these very legacy firms. The difference is overhead, not talent. Boyar doesn't carry the cost of 400+ employees, 20 physical offices, partner profit-sharing pools, and legacy technology infrastructure. That structural efficiency flows directly to the client as better pricing for equivalent expertise.</p></div>
    <div class="cl-mc"><h4>Jurisdiction comparison framework: <span class="cl-red">12 variables, one decision matrix.</span></h4><p>Every advisory engagement starts with a structured analytical framework: jurisdiction comparison across 12+ variables — tax rate, substance requirements, banking accessibility, regulatory burden, setup timeline, annual maintenance cost, treaty network, reputation index, licensing compatibility, talent availability, cost of living for relocated founders, and exit/restructuring flexibility. The client doesn't get an opinion — they get a decision matrix. This framework accomplishes two things simultaneously: it justifies the premium over Tier 1 mass incorporators (the client sees the analytical depth they're paying for), and it surfaces cross-sell opportunities organically. A jurisdiction comparison for a holding company reveals the case for a separate operating entity, or exposes a mismatch between personal tax residency and corporate structure. This is how a $15K company formation inquiry converts into a $45K full-structure mandate — not through upselling, but through rigorous analysis that shows the client what they actually need.</p></div>`,

    `<div class="cl-yhdr"><h2>The Acquisition <span class="cl-red">Engine</span></h2><div class="cl-yhdr-obj">A hybrid model deliberately weighted toward the Tier 3 referral model — achieving the acquisition economics of a 30-year-old firm within three years.</div></div>
    <div class="cl-block"><div class="cl-block-t">The Ignition vs the Fuel</div><p>Boyar does not intend to build a business dependent on perpetual marketing spend. The $17K paid media experiment in Year 1 is the ignition, not the fuel. By Year 2–3, the majority of new clients — targeting 60–70% — should come through referral channels: reciprocal referral partnerships with law firms and accountants; inbound referrals from satisfied clients (the named-advisor model creates natural word-of-mouth); referrals from Boyar Network partners (the Network functions as a distributed business development engine); and reputation-driven inbound from thought leadership and licensing expertise. The remaining 30–40% comes from targeted paid digital — not broad-spectrum Google Ads competing with mass incorporators for commodity keywords, but high-intent campaigns targeting licensing queries, HNWI relocation queries, and cross-border structuring queries where complexity signals a client who needs advisory.</p></div>
    <div class="cl-mc"><h4>Content strategy and referral development are <span class="cl-red">symbiotic, not separate channels.</span></h4><p>The paid media component also feeds the referral engine. A jurisdiction comparison guide promoted on LinkedIn gets shared by law firms and wealth advisors in their networks, seeding referral conversations. A referral-acquired client costs effectively zero to acquire, converts 20–30% higher, is 2–3x more likely to engage for multi-service mandates, and retains at significantly higher rates. By Year 3, if 65% of new clients come through referrals, Boyar's blended CAC drops from ~$2,500 to ~$800–$1,000 while lifetime value increases. This is the acquisition economics of a Tier 3 firm, achieved in three years rather than thirty.</p></div>
    <div class="cl-kpis"><div class="cl-kpi"><div class="cl-kpi-l">Year 1 Referral Target</div><div class="cl-kpi-v">40%</div></div><div class="cl-kpi"><div class="cl-kpi-l">Year 3 Referral Target</div><div class="cl-kpi-v cl-r">65–70%</div></div><div class="cl-kpi"><div class="cl-kpi-l">Referral CAC</div><div class="cl-kpi-v">~$0</div></div><div class="cl-kpi"><div class="cl-kpi-l">Direct Marketing CAC</div><div class="cl-kpi-v">~$2,500</div></div><div class="cl-kpi"><div class="cl-kpi-l">Blended CAC by Year 3</div><div class="cl-kpi-v cl-r">$800–$1,000</div></div><div class="cl-kpi"><div class="cl-kpi-l">Referral Conversion Premium</div><div class="cl-kpi-v">20–30% higher</div></div></div>`,

    `<div class="cl-yhdr"><h2>Why This <span class="cl-red">Positioning Scales</span></h2><div class="cl-yhdr-obj">A positioning that becomes more defensible over time — as expertise compounds, the network deepens, and the referral engine reaches self-sustaining velocity.</div></div>
    <div class="cl-mc"><h4>Neither tier can close the gap <span class="cl-red">— structurally.</span></h4><p>Mass incorporators cannot profitably add advisory depth — their economic model breaks the moment they add a human advisory layer. The moment you add a professional who actually understands jurisdictions, that professional's time costs money, and the commodity pricing that drives volume cannot support it. Legacy firms cannot economically deliver boutique attention to mid-market mandates — their overhead and competing priorities make it structurally impossible. A $50K client at a firm with $100M+ in revenue is not a priority. Advisors rotate. Response times stretch. The partner who won the engagement hands it to a junior associate.</p></div>
    <div class="cl-mc"><h4>Structuring as sole purpose is the only model that <span class="cl-red">compounds.</span></h4><p>Boyar sits in the gap that neither tier can close — the undivided attention of a specialist, the geographic reach of a generalist, the price point of neither, powered by an acquisition engine that progressively shifts toward the compounding referral model that the most enduring firms in this industry have always been built on. This is the essence of Boyar's competitive position: structuring as a vocation, not a transaction and not a subsidiary service. It is a positioning that becomes more defensible over time as expertise compounds, the network deepens, client relationships demonstrate the difference between formation-as-commodity, structuring-as-subset, and structuring-as-sole-purpose — and the referral engine reaches the self-sustaining velocity that transforms a young boutique into an enduring institution.</p></div>
    <div class="cl-closing"><h3>What Boyar Will Be Known For</h3><p>The firm that actually structures, not just incorporates. The firm that next-gen entrepreneurs and HNWIs choose because it speaks their language — digital-first, globally distributed, and quantitatively rigorous. The firm whose clients stay not because of a contract but because leaving would mean rebuilding institutional knowledge that took years to accumulate. That is the compounding competitive advantage that neither Tier 1 nor Tier 3 can replicate.</p></div>`
  ]
};
