export const competitorsData = {
  subtabs: ["Dixcart","Amicorp","Astons","Ocra Worldwide","Rosemont"],
  panels: [
    `<div class="cl-yhdr"><h2>Dixcart<br/><span class="cl-red">Founded 1972</span></h2><div class="cl-yhdr-obj">Family-owned, 7 offices across Crown Dependencies and Europe. Strong in trust administration and private client services for European HNWIs.</div></div>
    <div class="cl-stats"><div class="cl-stat"><div class="cl-stat-lbl">Founded</div><div class="cl-stat-val">1972</div></div><div class="cl-stat"><div class="cl-stat-lbl">Offices</div><div class="cl-stat-val">7</div></div><div class="cl-stat"><div class="cl-stat-lbl">Core Geography</div><div class="cl-stat-val">Europe + Crown Dependencies</div></div><div class="cl-stat"><div class="cl-stat-lbl">UAE / APAC Presence</div><div class="cl-stat-val cl-r">None</div></div></div>
    <div class="cl-block"><div class="cl-block-t">Full Analysis</div><p>Dixcart Group has operated for 50+ years as a family-owned TCSP with offices in the Isle of Man, Guernsey, Cyprus, Switzerland, Portugal, Latvia, and the UK. Their strength is deep expertise in traditional trust and corporate structures within European and Crown Dependency jurisdictions. Regulated for trust services in five jurisdictions, with a genuine depth of fiduciary knowledge that commands respect among private client advisors.</p><p>However, Dixcart has not expanded into the markets driving HNWI migration — UAE, Singapore, and the broader Asia-Pacific region. As 142,000 millionaires migrate annually (predominantly toward UAE, Singapore, and Australia), Dixcart's geographic footprint becomes a structural limitation. The firm also has no licensing advisory capability — it cannot advise clients on MiCA compliance, VASP licensing, or EMI authorization. For a crypto founder in Lisbon who needs a MiCA structure, Dixcart is not a viable option. For a family relocating to Dubai, Dixcart cannot execute in the destination jurisdiction.</p></div>
    <div class="cl-mc"><h4>Boyar's <span class="cl-red">Advantage</span></h4><p>The Boyar Network provides execution capability across the jurisdictions where Dixcart is absent — UAE, Singapore, Hong Kong, Cayman, BVI, Mauritius — while Boyar's licensing vertical captures an entire service category that Dixcart cannot offer. Additionally, Boyar's digital-native delivery model appeals to next-generation clients who find Dixcart's traditional approach outdated. For clients who have already engaged Dixcart for European structures and are now expanding globally, Boyar becomes the natural extension of their advisory relationship into jurisdictions Dixcart cannot reach.</p></div>`,

    `<div class="cl-yhdr"><h2>Amicorp<br/><span class="cl-red">Founded 1992</span></h2><div class="cl-yhdr-obj">40+ offices, ~700 employees. Full-service TCSP with global footprint and fund administration capability. Scale creates bureaucracy.</div></div>
    <div class="cl-stats"><div class="cl-stat"><div class="cl-stat-lbl">Founded</div><div class="cl-stat-val">1992</div></div><div class="cl-stat"><div class="cl-stat-lbl">Employees</div><div class="cl-stat-val">~700</div></div><div class="cl-stat"><div class="cl-stat-lbl">Offices</div><div class="cl-stat-val">40+</div></div><div class="cl-stat"><div class="cl-stat-lbl">Reputational Issue</div><div class="cl-stat-val cl-r">1MDB association</div></div></div>
    <div class="cl-block"><div class="cl-block-t">Full Analysis</div><p>Amicorp Group was founded in 1992 and has grown to approximately 700 employees across 40+ offices worldwide. The firm offers a comprehensive range of corporate, trust, fund, and compliance services — making it one of the most geographically diverse TCSPs in the market. The fund administration vertical ($7B+ AuA) represents genuine institutional depth.</p><p>Amicorp's weaknesses are structural. First, bureaucratic decision-making: clients report slow response times, complex internal approval processes, and difficulty reaching senior advisors. Second, the 1MDB association: Amicorp's historical involvement with entities connected to the 1MDB scandal, while legally resolved, continues to affect brand perception among compliance-sensitive institutional clients and onboarding processes at major banks. Third, commoditized service delivery: Amicorp's scale means that individual client relationships often lack the advisory depth that distinguishes a TCSP from an incorporation factory. The firm processes volume; it doesn't advise individuals.</p></div>
    <div class="cl-mc"><h4>Boyar's <span class="cl-red">Advantage</span></h4><p>Founder-led advisory where the senior decision-maker is directly accessible to every client. No institutional baggage or compliance history concerns that trigger enhanced due diligence at banking counterparties. The ability to offer equivalent jurisdictional coverage through the Boyar Network while maintaining boutique service quality — something Amicorp's institutional model cannot replicate. For clients who have been rejected by Amicorp due to compliance concerns, or frustrated by slow response times, Boyar offers the same multi-jurisdictional reach with none of the institutional friction.</p></div>`,

    `<div class="cl-yhdr"><h2>Astons<br/><span class="cl-red">Founded 1989</span></h2><div class="cl-yhdr-obj">Dubai-headquartered, strong in citizenship by investment and residency programs. A CBI firm, not a full-spectrum TCSP.</div></div>
    <div class="cl-stats"><div class="cl-stat"><div class="cl-stat-lbl">Founded</div><div class="cl-stat-val">1989</div></div><div class="cl-stat"><div class="cl-stat-lbl">HQ</div><div class="cl-stat-val">Dubai</div></div><div class="cl-stat"><div class="cl-stat-lbl">Primary Focus</div><div class="cl-stat-val">CBI / Residency</div></div><div class="cl-stat"><div class="cl-stat-lbl">Structuring Depth</div><div class="cl-stat-val cl-r">Limited</div></div></div>
    <div class="cl-block"><div class="cl-block-t">Full Analysis</div><p>Astons was founded in 1989 and is headquartered in Dubai, with offices in Cyprus, Malta, Greece, Turkey, and the USA. The firm has built its brand around helping HNWIs obtain second passports and establish residency in favorable jurisdictions — citizenship by investment in Caribbean programs, Cyprus, Malta, and similar. This is a legitimate and growing market, and Astons has carved out a credible position within it.</p><p>Astons' limitation is narrow service scope. The firm excels at CBI and immigration advisory but lacks the corporate structuring depth required for complex multi-jurisdictional arrangements. No fund administration. No licensing advisory. No complex trust services. A client who obtains a Cyprus or Caribbean passport through Astons still needs a separate advisor for company formation, trust establishment, banking relationships, and regulatory licensing. Astons cannot complete that picture.</p></div>
    <div class="cl-mc"><h4>Boyar's <span class="cl-red">Advantage</span></h4><p>Full-spectrum TCSP capability. Boyar can serve the same HNWI client from initial consultation through structure design, entity formation, banking facilitation, regulatory licensing, and ongoing administration — a complete lifecycle that Astons' CBI-focused model cannot match. For clients who have already engaged Astons for immigration, Boyar becomes the natural next-step advisor for the corporate structuring that follows: holding company formation, trust establishment, banking introductions in the new jurisdiction, and the ongoing compliance architecture that a second citizenship demands.</p></div>`,

    `<div class="cl-yhdr"><h2>Ocra Worldwide<br/><span class="cl-red">Founded 1989</span></h2><div class="cl-yhdr-obj">Commodity incorporator. High-volume, low-touch formation across 18 jurisdictions. The clearest example of what Boyar is not.</div></div>
    <div class="cl-stats"><div class="cl-stat"><div class="cl-stat-lbl">Founded</div><div class="cl-stat-val">1989</div></div><div class="cl-stat"><div class="cl-stat-lbl">Jurisdictions</div><div class="cl-stat-val">18+</div></div><div class="cl-stat"><div class="cl-stat-lbl">Advisory Capability</div><div class="cl-stat-val cl-r">None</div></div><div class="cl-stat"><div class="cl-stat-lbl">Model</div><div class="cl-stat-val">Pure formation factory</div></div></div>
    <div class="cl-block"><div class="cl-block-t">Full Analysis</div><p>Ocra Worldwide is a commodity incorporation firm operating across 18 jurisdictions. The firm's model is transactional: clients select a jurisdiction, pay a formation fee ($800–$2,000), and receive a shelf company or new incorporation with minimal advisory input. The service ends at certificate delivery. Ocra does not assess whether the client's chosen jurisdiction is optimal, does not design multi-jurisdictional structures, and does not provide ongoing corporate services or compliance advisory. Each client interaction is a one-time transaction with no relationship continuity.</p><p>Ocra's weakness is the absence of advisory capability. The firm has no licensing practice, no trust services, no banking introduction network, and no compliance advisory function. It is, in the most literal sense, a formation factory. The clients it cannot serve — those who need genuine structuring, banking, licensing, or ongoing compliance — are precisely Boyar's target market.</p></div>
    <div class="cl-mc"><h4>Boyar's <span class="cl-red">Advantage</span></h4><p>The advisory conversion model. Where Ocra processes a $1,500 formation and never speaks to the client again, Boyar's diagnostic approach converts 30% of equivalent formation inquiries into full structuring mandates worth $9K–$12K — a 6–8x revenue multiplier on the same initial inquiry. Moreover, Boyar's ongoing corporate services, compliance monitoring, and banking facilitation create recurring revenue from each client relationship that Ocra's transactional model cannot generate. Ocra's clients who need more are Boyar's referral pipeline.</p></div>`,

    `<div class="cl-yhdr"><h2>Rosemont (Monaco)<br/><span class="cl-red">Founded 2010</span></h2><div class="cl-yhdr-obj">Monaco-based boutique. High-end private client services. Excellent reputation within the Monaco/Riviera UHNWI community. Single jurisdiction.</div></div>
    <div class="cl-stats"><div class="cl-stat"><div class="cl-stat-lbl">Founded</div><div class="cl-stat-val">2010</div></div><div class="cl-stat"><div class="cl-stat-lbl">HQ</div><div class="cl-stat-val">Monaco</div></div><div class="cl-stat"><div class="cl-stat-lbl">Geographic Reach</div><div class="cl-stat-val cl-r">Single jurisdiction</div></div><div class="cl-stat"><div class="cl-stat-lbl">Licensing Capability</div><div class="cl-stat-val cl-r">None</div></div></div>
    <div class="cl-block"><div class="cl-block-t">Full Analysis</div><p>Rosemont is a Monaco-based boutique advisory firm focused on UHNWI clients. The firm's positioning is ultra-premium: luxury branding, exclusive client events, and personalized advisory relationships. Rosemont excels at serving the Monaco/Riviera UHNWI community with wealth structuring and family office advisory. The quality of individual client relationships is genuinely high — Rosemont is the rare boutique that delivers real advisory depth.</p><p>Rosemont's limitation is geographic concentration. The firm's expertise and relationships are centered on Monaco and, to a lesser extent, Western Europe. Clients with structuring needs in Asia-Pacific, the Middle East, or the Americas must look elsewhere. Additionally, Rosemont has no licensing advisory capability — the firm does not assist with regulatory applications for financial services, crypto, or fund management. For a Monaco-based UHNWI whose family business is expanding into UAE or Singapore, Rosemont cannot follow.</p></div>
    <div class="cl-mc"><h4>Boyar's <span class="cl-red">Advantage</span></h4><p>Multi-jurisdictional execution. While Rosemont serves Monaco-based UHNWIs in a single jurisdiction, Boyar's Network enables structuring across 53 jurisdictions — capturing the same UHNWI client segment but with the ability to execute wherever the client's business, investments, or family require. Boyar also brings licensing capability that Rosemont lacks, making Boyar the more comprehensive advisory partner for clients with regulatory needs beyond simple wealth structuring. For clients who prize boutique attention (as Rosemont's clients do) but need global reach, Boyar is the natural alternative.</p></div>`
  ]
};
