export const risksData = {
  subtabs: ["Founder Dependency","MiCA Timeline","Client Concentration","Banking Fragility","Competitive Pressure","Regulatory Changes"],
  panels: [
    `<div class="cl-yhdr"><h2>Single-Founder Dependency<br/><span class="cl-sev-h">High Severity</span></h2><div class="cl-yhdr-obj">All client relationships, business development, and institutional knowledge reside with the founder in Year 1–2. The most immediate execution risk.</div></div>
    <div class="cl-stats"><div class="cl-stat"><div class="cl-stat-lbl">Severity</div><div class="cl-stat-val cl-r">HIGH</div></div><div class="cl-stat"><div class="cl-stat-lbl">First Hire Timeline</div><div class="cl-stat-val">Mid Year 2</div></div><div class="cl-stat"><div class="cl-stat-lbl">Relationships Delegated by Y2</div><div class="cl-stat-val">30–40%</div></div></div>
    <div class="cl-mc"><h4>Mitigant <span class="cl-red">Strategy</span></h4><p>The single-founder model is a deliberate Year 1–2 design choice, not an oversight. The constraint on scale forces discipline in client selection — every mandate must be a reference case. Specific mitigants: (1) Phased hiring plan — first associate in Year 2 when revenue triggers justify it, structured team by Year 3. (2) Deliberate pacing — client acquisition is limited to match execution capacity, preventing quality degradation. (3) Process documentation — every client workflow is documented in sufficient detail that a trained associate can execute it. (4) Key person insurance secured in Year 1. (5) Boyar Network partner firms can absorb client administration if the founder is temporarily unavailable. The goal is to make the founder's personal involvement a quality differentiator in Year 1, not a single point of failure by Year 3. By mid-Year 2, the first senior hire independently manages 30–40% of relationships. All structuring documentation and relationship histories are systematically captured.</p></div>`,

    `<div class="cl-yhdr"><h2>MiCA Timeline Shifts<br/><span class="cl-sev-h">High Severity</span></h2><div class="cl-yhdr-obj">The MiCA deadline has already been subject to national transitional extensions. A deferral shifts — but does not eliminate — licensing demand.</div></div>
    <div class="cl-stats"><div class="cl-stat"><div class="cl-stat-lbl">Severity</div><div class="cl-stat-val cl-r">HIGH</div></div><div class="cl-stat"><div class="cl-stat-lbl">MiCA Hard Deadline</div><div class="cl-stat-val">July 1, 2026</div></div><div class="cl-stat"><div class="cl-stat-lbl">Revenue at Risk if Delayed</div><div class="cl-stat-val">$150K–$300K shift</div></div><div class="cl-stat"><div class="cl-stat-lbl">Licensing Verticals Beyond MiCA</div><div class="cl-stat-val cl-r">5+</div></div></div>
    <div class="cl-mc"><h4>Mitigant <span class="cl-red">Strategy</span></h4><p>MiCA enforcement is already in progress — the regulation entered into force in June 2023, with CASP authorization requirements taking effect July 1, 2026. While transition periods could be extended, the regulatory infrastructure is deployed and irreversible. Specific mitigants: (1) Boyar's revenue model is not MiCA-dependent — formation, structuring, and corporate services generate baseline revenue independent of any single regulatory event. (2) Even if the MiCA deadline shifts by 6–12 months, the licensing demand doesn't disappear — it defers. Clients who need VASP authorization will need it eventually. (3) The licensing vertical is not mono-regulatory. iGaming licensing (Curacao new model, Malta Gaming Authority), EMI/MSB licensing, and forex licensing continue independently of MiCA timeline. Revenue projections never depend on a single regulatory catalyst. The worst-case scenario: MiCA licensing revenue shifts from Year 2 to Year 3, reducing Year 2 revenue by $150K–$300K but not threatening the firm's viability.</p></div>`,

    `<div class="cl-yhdr"><h2>Client Concentration<br/><span class="cl-sev-m">Medium Severity</span></h2><div class="cl-yhdr-obj">In Year 1, the top 3 clients could represent 50–60% of revenue. Concentration risk is a mathematical inevitability of early stage — managed through deliberate diversification.</div></div>
    <div class="cl-stats"><div class="cl-stat"><div class="cl-stat-lbl">Severity</div><div class="cl-stat-val" style="color:#f59e0b">MEDIUM</div></div><div class="cl-stat"><div class="cl-stat-lbl">Year 1 Concentration Risk</div><div class="cl-stat-val cl-r">Top 3 = 50–60%</div></div><div class="cl-stat"><div class="cl-stat-lbl">Year 3 Target</div><div class="cl-stat-val">No client &gt;15%</div></div><div class="cl-stat"><div class="cl-stat-lbl">Year 5 Target</div><div class="cl-stat-val">No client &gt;10%</div></div></div>
    <div class="cl-mc"><h4>Mitigant <span class="cl-red">Strategy</span></h4><p>Client concentration is a mathematical inevitability in Year 1–2 (small client base, high-value mandates). Specific mitigants: (1) Target no single client exceeding 15% of annual revenue by Year 3, and 10% by Year 5. (2) Actively diversify the pipeline across service lines (formation, structuring, licensing, corporate services) and client segments (HNWI families, crypto firms, traditional corporates). The paid media experiment in Year 1 deliberately targets 5 distinct regions to ensure pipeline diversification from the outset. (3) Build recurring revenue (corporate services renewals) that provides a diversified revenue base independent of any single mandate — by Year 3, renewals from 22+ entities represent $56K in recurring revenue at zero concentration risk. (4) Maintain pipeline discipline — even when a large mandate is tempting, ensure that smaller mandates continue to flow to prevent concentration creep. The renewal flywheel naturally dilutes concentration as the client base grows.</p></div>`,

    `<div class="cl-yhdr"><h2>Banking Relationship Fragility<br/><span class="cl-sev-m">Medium Severity</span></h2><div class="cl-yhdr-obj">Partner banks may change policies, exit client segments, or terminate TCSP relationships with minimal notice. Banking access is the most fragile link in the value chain.</div></div>
    <div class="cl-stats"><div class="cl-stat"><div class="cl-stat-lbl">Severity</div><div class="cl-stat-val" style="color:#f59e0b">MEDIUM</div></div><div class="cl-stat"><div class="cl-stat-lbl">Target Banking Partners</div><div class="cl-stat-val cl-r">8–10</div></div><div class="cl-stat"><div class="cl-stat-lbl">Partners per Key Jurisdiction</div><div class="cl-stat-val">3–5</div></div></div>
    <div class="cl-mc"><h4>Mitigant <span class="cl-red">Strategy</span></h4><p>Banking relationships are the most fragile link in the TCSP value chain. Banks may change policies, exit client segments, increase due diligence requirements, or terminate TCSP relationships with minimal notice. Specific mitigants: (1) Maintain 3–5 banking relationships per key jurisdiction — no single banking partner should be a bottleneck for any client type or jurisdiction. (2) Build the Boyar Network's banking referral capacity so that banking facilitation is distributed across multiple network partners, not concentrated in Boyar's direct relationships. (3) Develop relationships with digital banks and fintech banking platforms (EMI-licensed institutions, neo-banks for corporates) that are more receptive to TCSP-introduced clients and operate with faster onboarding timelines. (4) Provide banking partners with consistently high-quality due diligence packages, reducing their compliance burden and making Boyar a preferred introduction source rather than a generic agent. The licensing vertical strengthens banking access — a licensed VASP is easier to bank than an unlicensed one, and completed licensing mandates become the primary reference for banking partner relationships.</p></div>`,

    `<div class="cl-yhdr"><h2>Competitive Pressure from Larger TCSPs<br/><span class="cl-sev-m">Medium Severity</span></h2><div class="cl-yhdr-obj">TMF, Vistra, or IQ-EQ could launch boutique tiers targeting mid-market clients. Large platforms structurally cannot replicate boutique attention.</div></div>
    <div class="cl-stats"><div class="cl-stat"><div class="cl-stat-lbl">Severity</div><div class="cl-stat-val" style="color:#f59e0b">MEDIUM</div></div><div class="cl-stat"><div class="cl-stat-lbl">Sovereign/Vistra Coexistence</div><div class="cl-stat-val">Decades</div></div><div class="cl-stat"><div class="cl-stat-lbl">Platform Economics Barrier</div><div class="cl-stat-val cl-r">Structural</div></div></div>
    <div class="cl-mc"><h4>Mitigant <span class="cl-red">Strategy</span></h4><p>Competitive threats come from two directions: Tier 1 mass incorporators moving upmarket into advisory structuring, and Tier 3 legacy firms investing in digital delivery and licensing capability. Specific mitigants: (1) The advisory moat — genuine advisory conversion (30% of formation inquiries to full structures) requires expertise and credibility that cannot be bought or quickly built. The knowledge compounds with each completed mandate. (2) The licensing moat — MiCA/VASP licensing capability requires deep regulatory knowledge that takes years of mandate experience to develop. A competitor entering in 2028 needs 2–3 years to reach Boyar's depth. (3) The relationship moat — founder-led client relationships with direct access to senior decision-makers cannot be replicated by institutional firms with rotating relationship managers. (4) Speed advantage — by the time competitors recognize and respond to Boyar's positioning, the firm will have 3–5 years of executed mandates, established relationships, and compounding brand equity. Large platforms structurally cannot replicate boutique attention: their cost structures make it uneconomical to service $30K–$75K mandates with depth. Sovereign has coexisted with Vistra for decades because this segment prefers personal service.</p></div>`,

    `<div class="cl-yhdr"><h2>Regulatory Changes in Key Jurisdictions<br/><span class="cl-sev-h">High Severity</span></h2><div class="cl-yhdr-obj">A major jurisdiction could change its tax regime or substance requirements. Every restructuring triggered by regulatory change is itself a billable engagement.</div></div>
    <div class="cl-stats"><div class="cl-stat"><div class="cl-stat-lbl">Severity</div><div class="cl-stat-val cl-r">HIGH</div></div><div class="cl-stat"><div class="cl-stat-lbl">Max Single Jurisdiction Revenue</div><div class="cl-stat-val">15% by Year 3</div></div><div class="cl-stat"><div class="cl-stat-lbl">Jurisdictions in Coverage</div><div class="cl-stat-val cl-r">53</div></div></div>
    <div class="cl-mc"><h4>Mitigant <span class="cl-red">Strategy</span></h4><p>Regulatory risk is bidirectional: increased enforcement creates advisory demand (positive for Boyar), while regulatory relaxation could reduce compliance obligations and advisory budgets (negative). Specific mitigants: (1) Boyar's advisory model is regulation-agnostic — the firm helps clients comply with whatever framework applies, rather than betting on any specific regulatory outcome. (2) The trend is unidirectional toward more regulation, more categories, and more compliance requirements. Even in jurisdictions that relax specific rules, the overall compliance surface area continues to expand. (3) The 53-jurisdiction coverage is designed for regulatory resilience. No single jurisdiction exceeds 15% of revenue by Year 3. Every restructuring triggered by regulatory change in any jurisdiction is itself a billable engagement — clients need new structures, new compliance frameworks, and new banking relationships when jurisdictions change their rules. (4) When a jurisdiction changes, Boyar's clients need to restructure. That restructuring is Boyar's mandate. Regulatory change is not a threat to the business model — it is a demand generator.</p></div>`
  ]
};
