/** @format */

"use client";

const jurisdictions = [
	{
		region: "Andorra",
		eligibility: "Offshore Companies, Onshore Companies, Local Companies",
		currencies: "USD, EUR, CHF, CAD, AUD, SEK, NOK, NZD",
		services:
			"Transactional Banking, Discretionary Wealth Management, Brokerage/Securities, Debit/Credit Card, Lombard Loans",
		personalVisit: "Not required",
		openingTime: "N/A",
		fees: "N/A",
	},
	{
		region: "Antigua and Barbuda",
		eligibility: "Offshore Companies, Onshore Companies",
		currencies: "USD, EUR, GBP",
		services:
			"Transactional Banking, Debit/Credit Card, Discretionary Wealth Management",
		personalVisit: "Not required",
		openingTime: "N/A",
		fees: "N/A",
	},
	{
		region: "Armenia",
		eligibility: "Offshore Companies, Onshore Companies, Local Companies",
		currencies: "EUR, USD, RUB, AMD",
		services:
			"Transactional Banking, Payment Processing, Discretionary Wealth Management, Debit/Credit Card",
		personalVisit: "Not required",
		openingTime: "1–2 weeks",
		fees: "EUR 4,500",
	},
	{
		region: "Bahamas",
		eligibility: "Offshore Companies, Onshore Companies, Local Companies",
		currencies: "USD, EUR, Multicurrency",
		services:
			"Transactional Banking, Brokerage/Securities, Lombard Loans, Discretionary Wealth Management, Debit/Credit Card, Trade Finance, Payment Processing",
		personalVisit: "Not required",
		openingTime: "9–13 days",
		fees: "EUR 6,000",
	},
	{
		region: "Barbados",
		eligibility: "Local Companies",
		currencies: "Multicurrency",
		services: "Transactional Banking, Trade Finance, Debit/Credit Card",
		personalVisit: "Not required",
		openingTime: "N/A",
		fees: "N/A",
	},
	{
		region: "Belize",
		eligibility: "Offshore Companies, Onshore Companies",
		currencies:
			"EUR, GBP, USD, CAD, CHF, AUD, AED, CNY, SEK, NOK, Multicurrency",
		services:
			"Transactional Banking, Lombard Loans, Payment Processing, Debit/Credit Card",
		personalVisit: "Not required",
		openingTime: "7–12 days",
		fees: "EUR 4,700 / EUR 4,800",
	},
	{
		region: "Bermuda",
		eligibility: "Local Companies",
		currencies: "Multicurrency",
		services:
			"Lombard Loans, Debit/Credit Card, Transactional Banking, Brokerage/Securities",
		personalVisit: "Not required",
		openingTime: "N/A",
		fees: "N/A",
	},
	{
		region: "British Virgin Islands",
		eligibility: "Offshore Companies, Onshore Companies, Local Companies",
		currencies: "USD, GBP, HKD, CAD, EUR, Multicurrency",
		services:
			"Transactional Banking, Discretionary Wealth Management, Lombard Loans, Trade Finance, Payment Processing, Brokerage/Securities, Debit/Credit Card",
		personalVisit: "Not required",
		openingTime: "9–15 days",
		fees: "EUR 4,400",
	},
	{
		region: "Bulgaria",
		eligibility: "Onshore Companies",
		currencies: "EUR, USD",
		services: "Transactional Banking, Debit/Credit Card, SEPA, SWIFT",
		personalVisit: "Not required",
		openingTime: "3–6 days / 9–10 days",
		fees: "EUR 5,000 / EUR 4,900",
	},
	{
		region: "Cayman Islands",
		eligibility: "Local Companies, Offshore Companies, Onshore Companies",
		currencies: "USD, EUR, GBP, CAD, AUD, JPY, SEK, CHF, Multicurrency",
		services:
			"Transactional Banking, Lombard Loans, Payment Processing, Debit/Credit Card, Brokerage/Securities, Discretionary Wealth Management, Trade Finance",
		personalVisit: "Not required",
		openingTime: "N/A",
		fees: "N/A",
	},
	{
		region: "Cyprus",
		eligibility: "Local Companies, Onshore Companies, Offshore Companies",
		currencies: "EUR, Multicurrency",
		services: "Debit/Credit Card, Transactional Banking, Payment Processing",
		personalVisit: "Required",
		openingTime: "8–10 days / 5–9 days",
		fees: "EUR 6,750 / EUR 4,700",
	},
	{
		region: "Cook Islands",
		eligibility: "Offshore Companies, Onshore Companies, Local Companies",
		currencies: "USD, EUR, GBP, CAD, NZD, AUD, SGD, HKD",
		services:
			"Transactional Banking, Discretionary Wealth Management, Brokerage/Securities, Debit/Credit Card",
		personalVisit: "Not required",
		openingTime: "N/A",
		fees: "N/A",
	},
	{
		region: "Curaçao",
		eligibility: "Local Companies, Offshore Companies, Onshore Companies",
		currencies: "USD, Multicurrency",
		services:
			"Transactional Banking, Lombard Loans, Discretionary Wealth Management, Debit/Credit Card",
		personalVisit: "Not required",
		openingTime: "N/A",
		fees: "N/A",
	},
	{
		region: "Czech Republic",
		eligibility: "Offshore Companies, Onshore Companies",
		currencies: "EUR, GBP, SGD, CZK, CHF",
		services:
			"Transactional Banking, Payment Processing, Debit/Credit Card, Crypto Integration",
		personalVisit: "Not required",
		openingTime: "2 weeks",
		fees: "EUR 4,500",
	},
	{
		region: "Dominica",
		eligibility: "Offshore Companies, Onshore Companies, Local Companies",
		currencies: "USD, EUR, GBP, Multicurrency",
		services: "Transactional Banking, Brokerage/Securities, Debit/Credit Card",
		personalVisit: "Not required",
		openingTime: "5–6 days / 5–7 days / 1 week",
		fees: "EUR 4,500 / EUR 4,700 / EUR 5,000",
	},
	{
		region: "Estonia",
		eligibility: "Onshore Companies, Local Companies",
		currencies: "EUR",
		services:
			"Transactional Banking, Discretionary Wealth Management, Brokerage/Securities",
		personalVisit: "Required",
		openingTime: "N/A",
		fees: "N/A",
	},
	{
		region: "Germany",
		eligibility: "Onshore Companies",
		currencies: "EUR",
		services: "Transactional Banking, SEPA, SWIFT",
		personalVisit: "Not required",
		openingTime: "10 days",
		fees: "EUR 5,400",
	},
	{
		region: "Gibraltar",
		eligibility: "Offshore Companies, Onshore Companies, Local Companies",
		currencies: "USD, EUR, GBP, Multicurrency",
		services:
			"Transactional Banking, Brokerage/Securities, Discretionary Wealth Management, Debit/Credit Card",
		personalVisit: "Not required",
		openingTime: "N/A",
		fees: "N/A",
	},
	{
		region: "Hong Kong",
		eligibility: "Offshore Companies, Onshore Companies, Local Companies",
		currencies: "HKD, USD, Multicurrency",
		services:
			"Transactional Banking, Lombard Loans, Trade Finance, Payment Processing, Discretionary Wealth Management, Debit/Credit Card",
		personalVisit: "Not required",
		openingTime: "N/A",
		fees: "N/A",
	},
	{
		region: "Ireland",
		eligibility: "Local Companies",
		currencies: "EUR, Multicurrency",
		services: "Transactional Banking, Lombard Loans, Debit/Credit Card",
		personalVisit: "Not required",
		openingTime: "3–4 days",
		fees: "EUR 4,500",
	},
	{
		region: "Isle of Man",
		eligibility: "Local Companies, Offshore Companies, Onshore Companies",
		currencies:
			"USD, AUD, EUR, CZK, DKK, HUF, SGD, JPY, NOK, GBP, ZAR, ILS, NZD, PLN, CHF, SEK, CAD, BGN",
		services:
			"Transactional Banking, Discretionary Wealth Management, Brokerage/Securities, Debit/Credit Card",
		personalVisit: "Not required",
		openingTime: "2–3 days",
		fees: "EUR 7,000",
	},
	{
		region: "Kazakhstan",
		eligibility: "Offshore Companies, Onshore Companies, Local Companies",
		currencies: "Multicurrency",
		services: "Transactional Banking",
		personalVisit: "Not required",
		openingTime: "N/A",
		fees: "N/A",
	},
	{
		region: "Labuan",
		eligibility: "Offshore Companies, Onshore Companies, Local Companies",
		currencies:
			"USD, JPY, SGD, EUR, GBP, Multicurrency, CAD, CHF, HKD, THB, AED",
		services: "Transactional Banking",
		personalVisit: "Not required",
		openingTime: "N/A",
		fees: "N/A",
	},
	{
		region: "Latvia",
		eligibility: "Onshore Companies",
		currencies: "EUR",
		services: "Transactional Banking, SEPA, SWIFT",
		personalVisit: "Not required",
		openingTime: "8–10 days / 9–11 days",
		fees: "EUR 6,500 / EUR 5,500",
	},
	{
		region: "Liechtenstein",
		eligibility: "Onshore Companies, Local Companies, Offshore Companies",
		currencies: "CHF, EUR, Multicurrency",
		services:
			"Debit/Credit Card, Discretionary Wealth Management, Brokerage/Securities",
		personalVisit: "Not required",
		openingTime: "5–12 days / 2 weeks",
		fees: "EUR 7,000 / EUR 6,500",
	},
	{
		region: "Lithuania",
		eligibility: "Onshore Companies, Local Companies, Offshore Companies",
		currencies:
			"EUR, PLN, CNY, HUF, Multicurrency, CAD, GBP, CHF, HKD, USD, SEK, JPY",
		services: "Transactional Banking, Payment Processing, Debit/Credit Card",
		personalVisit: "Not required",
		openingTime: "5–12 days / 7–10 days / 7–9 days / 10–12 days / 5–6 days",
		fees: "EUR 4,500 / EUR 4,300 / EUR 4,900 / EUR 6,500 / EUR 5,400 / EUR 4,800",
	},
	{
		region: "Luxembourg",
		eligibility: "Onshore Companies, Local Companies, Offshore Companies",
		currencies: "EUR, Multicurrency",
		services: "Transactional Banking, Debit/Credit Card, Payment Processing",
		personalVisit: "Not required",
		openingTime: "8–12 days",
		fees: "EUR 6,900",
	},
	{
		region: "Malta",
		eligibility: "Onshore Companies, Local Companies",
		currencies: "EUR, Multicurrency",
		services: "—",
		personalVisit: "Not required",
		openingTime: "10–14 days / 7–12 days",
		fees: "EUR 6,500 / EUR 4,850",
	},
	{
		region: "Mauritius",
		eligibility: "Offshore Companies, Onshore Companies, Local Companies",
		currencies: "Multicurrency",
		services:
			"Discretionary Wealth Management, Transactional Banking, Brokerage/Securities, Debit/Credit Card",
		personalVisit: "Not required",
		openingTime: "3–4 days",
		fees: "EUR 4,750",
	},
	{
		region: "Nevis",
		eligibility: "Offshore / Private Clients",
		currencies: "USD, EUR, GBP",
		services:
			"Personal Banking, Trust & Escrow, Asset Management, Investment Advisory",
		personalVisit: "Not required",
		openingTime: "6–7 days / 8–9 days",
		fees: "EUR 4,900 / EUR 5,200",
	},
	{
		region: "Panama",
		eligibility: "Offshore Companies, Onshore Companies, Local Companies",
		currencies: "USD, EUR, CAD, CHF, GBP",
		services:
			"Transactional Banking, Debit/Credit Card, Discretionary Wealth Management, Lombard Loans",
		personalVisit: "Not required",
		openingTime: "N/A",
		fees: "N/A",
	},
	{
		region: "Puerto Rico",
		eligibility: "Offshore Companies, Onshore Companies, Local Companies",
		currencies:
			"USD, HKD, AUD, CAD, CHF, CNY, DKK, EUR, GBP, JPY, NOK, NZD, SEK, SGD, TRY, ZAR, Multicurrency",
		services:
			"Transactional Banking, Debit/Credit Card, Payment Processing, Trade Finance",
		personalVisit: "Not required",
		openingTime: "4–7 days / 7–10 days / 10–12 days",
		fees: "EUR 5,500 / EUR 5,250 / EUR 5,100",
	},
	{
		region: "Saint Kitts and Nevis",
		eligibility: "Offshore Companies, Onshore Companies, Local Companies",
		currencies:
			"USD, EUR, GBP, CHF, AUD, CAD, AED, JPY, SGD, HKD, Multicurrency",
		services:
			"Transactional Banking, Discretionary Wealth Management, Brokerage/Securities",
		personalVisit: "Not required",
		openingTime: "N/A",
		fees: "N/A",
	},
	{
		region: "Saint Lucia",
		eligibility: "Offshore Companies, Onshore Companies",
		currencies:
			"USD, EUR, GBP, HKD, CAD, CHF, AED, AUD, NZD, NOK, SEK, THB, JPY, ZAR, Multicurrency",
		services: "Transactional Banking, Debit/Credit Card",
		personalVisit: "Not required",
		openingTime: "5–7 days",
		fees: "EUR 4,000",
	},
	{
		region: "Saint Vincent and the Grenadines",
		eligibility: "Offshore Companies, Onshore Companies",
		currencies: "USD, EUR, GBP, CHF, CAD",
		services: "Transactional Banking",
		personalVisit: "Not required",
		openingTime: "10–12 days",
		fees: "EUR 5,500",
	},
	{
		region: "Seychelles",
		eligibility: "Offshore Companies, Onshore Companies",
		currencies: "USD",
		services: "Transactional Banking",
		personalVisit: "Not required",
		openingTime: "N/A",
		fees: "N/A",
	},
	{
		region: "Singapore",
		eligibility: "Offshore Companies, Onshore Companies, Local Companies",
		currencies:
			"USD, SGD, EUR, GBP, NZD, RMB, AUD, JPY, HKD, CHF, CAD, Multicurrency",
		services: "Transactional Banking, Debit/Credit Card",
		personalVisit: "Not required",
		openingTime: "N/A",
		fees: "N/A",
	},
	{
		region: "Slovakia",
		eligibility: "Onshore Companies",
		currencies: "EUR, USD, GBP, CHF, CAD",
		services: "Transactional Banking, SEPA, SWIFT",
		personalVisit: "Not required",
		openingTime: "6–8 days",
		fees: "EUR 4,900",
	},
	{
		region: "Spain",
		eligibility: "Offshore Companies, Onshore Companies",
		currencies: "EUR, USD",
		services: "Transactional Banking, SEPA, SWIFT",
		personalVisit: "Not required",
		openingTime: "10–14 days",
		fees: "EUR 5,750",
	},
	{
		region: "Switzerland",
		eligibility: "Offshore Companies, Onshore Companies, Local Companies",
		currencies:
			"EUR, GBP, CHF, CAD, AUD, JPY, SGD, PLN, HKD, NOK, SEK, ILS, MXN, DKK, TRY, NZD, AED, Multicurrency",
		services:
			"Debit/Credit Card, Discretionary Wealth Management, Brokerage/Securities, Transactional Banking",
		personalVisit: "Not required",
		openingTime: "6–10 days / 10–15 days / 14–20 days / 10–20 days",
		fees: "EUR 6,250 / EUR 7,000 / EUR 6,800 / EUR 7,000",
	},
	{
		region: "United Kingdom",
		eligibility: "Offshore Companies, Onshore Companies, Local Companies",
		currencies: "EUR, GBP, USD, CAD, Multicurrency",
		services: "Transactional Banking, Payment Processing, Debit/Credit Card",
		personalVisit: "Not required",
		openingTime: "4–5 days / 5–7 days / 7–10 days / 7–8 days",
		fees: "EUR 5,200 / EUR 4,150 / EUR 6,000 / EUR 4,600 / EUR 3,900",
	},
	{
		region: "USA",
		eligibility: "Offshore Companies, Onshore Companies, Local Companies",
		currencies: "USD, Multicurrency",
		services:
			"Transactional Banking, Payment Processing, Lombard Loans, Debit/Credit Card, Discretionary Wealth Management",
		personalVisit: "Not required",
		openingTime: "12–18 days / 8–12 days",
		fees: "EUR 5,000 / EUR 4,100",
	},
	{
		region: "Vanuatu",
		eligibility: "Local Companies, Offshore Companies, Onshore Companies",
		currencies: "USD, EUR, GBP",
		services:
			"Transactional Banking, Trade Finance, Discretionary Wealth Management",
		personalVisit: "Not required",
		openingTime: "N/A",
		fees: "N/A",
	},
];
